[package]
name = "soiboy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
modular-bitfield = "0.11"
flate2 = "1.0"
binrw = "0.11"

[dev-dependencies]
x-flipper-360 = { git = "https://github.com/offsetting/x-flipper-360" }
