[package]
name = "soiboy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
modular-bitfield = "0.11"
serde_json = "1.0"
flate2 = "1.0"
anyhow = "1.0"
binrw = "0.8"
x-flipper-360 = { git = "https://github.com/offsetting/x-flipper-360" }
